### ISSUE TITLE
ros2 launch vision_msgs_rviz_plugins test_all.launch.py is error

### ISSUE THREAD

**Issue by linClubs** [Kukanani/vision_msgs_proposal#98]
hi, my env  ros2-galactic, I run :

ros2 launch vision_msgs_rviz_plugins test_all.launch.py , the command show as follow, how I fix it?

---

~~~
[INFO] [launch]: All log files can be found below /home/lin/.ros/log/2023-08-22-15-17-03-064993-PC-80592
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [BoundingBox3D.py-1]: process started with pid [80594]
[INFO] [BoundingBox3DArray.py-2]: process started with pid [80596]
[INFO] [Detection3D.py-3]: process started with pid [80598]
[INFO] [Detection3DArray.py-4]: process started with pid [80600]
[INFO] [rviz2-5]: process started with pid [80602]
[Detection3D.py-3] Traceback (most recent call last):
[Detection3D.py-3]   File "/home/lin/ros2_code/pillars_ws/install/vision_msgs_rviz_plugins/lib/vision_msgs_rviz_plugins/Detection3D.py", line 23, in <module>
[Detection3D.py-3]     from rclpy.node import Node
[Detection3D.py-3]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/node.py", line 43, in <module>
[Detection3D.py-3]     from rclpy.client import Client
[Detection3D.py-3]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/client.py", line 22, in <module>
[Detection3D.py-3]     from rclpy.impl.implementation_singleton import rclpy_implementation as _rclpy
[Detection3D.py-3]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/impl/implementation_singleton.py", line 32, in <module>
[Detection3D.py-3]     rclpy_implementation = import_c_library('._rclpy_pybind11', package)
[Detection3D.py-3]   File "/opt/ros/galactic/lib/python3.8/site-packages/rpyutils/import_c_library.py", line 39, in import_c_library
[Detection3D.py-3]     return importlib.import_module(name, package=package)
[Detection3D.py-3]   File "/home/lin/software/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
[Detection3D.py-3]     return _bootstrap._gcd_import(name[level:], package, level)
[Detection3D.py-3] ModuleNotFoundError: No module named 'rclpy._rclpy_pybind11'
[Detection3D.py-3] The C extension '/opt/ros/galactic/lib/python3.8/site-packages/_rclpy_pybind11.cpython-39-x86_64-linux-gnu.so' isn't present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system' for possible solutions
[BoundingBox3DArray.py-2] Traceback (most recent call last):
[BoundingBox3DArray.py-2]   File "/home/lin/ros2_code/pillars_ws/install/vision_msgs_rviz_plugins/lib/vision_msgs_rviz_plugins/BoundingBox3DArray.py", line 22, in <module>
[BoundingBox3DArray.py-2]     from rclpy.node import Node
[BoundingBox3DArray.py-2]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/node.py", line 43, in <module>
[BoundingBox3DArray.py-2]     from rclpy.client import Client
[BoundingBox3DArray.py-2]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/client.py", line 22, in <module>
[BoundingBox3DArray.py-2]     from rclpy.impl.implementation_singleton import rclpy_implementation as _rclpy
[BoundingBox3DArray.py-2]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/impl/implementation_singleton.py", line 32, in <module>
[BoundingBox3DArray.py-2]     rclpy_implementation = import_c_library('._rclpy_pybind11', package)
[BoundingBox3DArray.py-2]   File "/opt/ros/galactic/lib/python3.8/site-packages/rpyutils/import_c_library.py", line 39, in import_c_library
[BoundingBox3DArray.py-2]     return importlib.import_module(name, package=package)
[BoundingBox3DArray.py-2]   File "/home/lin/software/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
[BoundingBox3DArray.py-2]     return _bootstrap._gcd_import(name[level:], package, level)
[BoundingBox3DArray.py-2] ModuleNotFoundError: No module named 'rclpy._rclpy_pybind11'
[BoundingBox3DArray.py-2] The C extension '/opt/ros/galactic/lib/python3.8/site-packages/_rclpy_pybind11.cpython-39-x86_64-linux-gnu.so' isn't present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system' for possible solutions
[BoundingBox3D.py-1] Traceback (most recent call last):
[BoundingBox3D.py-1]   File "/home/lin/ros2_code/pillars_ws/install/vision_msgs_rviz_plugins/lib/vision_msgs_rviz_plugins/BoundingBox3D.py", line 22, in <module>
[BoundingBox3D.py-1]     from rclpy.node import Node
[BoundingBox3D.py-1]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/node.py", line 43, in <module>
[BoundingBox3D.py-1]     from rclpy.client import Client
[BoundingBox3D.py-1]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/client.py", line 22, in <module>
[BoundingBox3D.py-1]     from rclpy.impl.implementation_singleton import rclpy_implementation as _rclpy
[BoundingBox3D.py-1]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/impl/implementation_singleton.py", line 32, in <module>
[BoundingBox3D.py-1]     rclpy_implementation = import_c_library('._rclpy_pybind11', package)
[BoundingBox3D.py-1]   File "/opt/ros/galactic/lib/python3.8/site-packages/rpyutils/import_c_library.py", line 39, in import_c_library
[BoundingBox3D.py-1]     return importlib.import_module(name, package=package)
[BoundingBox3D.py-1]   File "/home/lin/software/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
[BoundingBox3D.py-1]     return _bootstrap._gcd_import(name[level:], package, level)
[BoundingBox3D.py-1] ModuleNotFoundError: No module named 'rclpy._rclpy_pybind11'
[BoundingBox3D.py-1] The C extension '/opt/ros/galactic/lib/python3.8/site-packages/_rclpy_pybind11.cpython-39-x86_64-linux-gnu.so' isn't present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system' for possible solutions
[ERROR] [Detection3D.py-3]: process has died [pid 80598, exit code 1, cmd '/home/lin/ros2_code/pillars_ws/install/vision_msgs_rviz_plugins/lib/vision_msgs_rviz_plugins/Detection3D.py --ros-args -r __node:=detection3d_test'].
[ERROR] [BoundingBox3DArray.py-2]: process has died [pid 80596, exit code 1, cmd '/home/lin/ros2_code/pillars_ws/install/vision_msgs_rviz_plugins/lib/vision_msgs_rviz_plugins/BoundingBox3DArray.py --ros-args -r __node:=boundingbox3darray_test'].
[Detection3DArray.py-4] Traceback (most recent call last):
[Detection3DArray.py-4]   File "/home/lin/ros2_code/pillars_ws/install/vision_msgs_rviz_plugins/lib/vision_msgs_rviz_plugins/Detection3DArray.py", line 22, in <module>
[Detection3DArray.py-4]     from rclpy.node import Node
[Detection3DArray.py-4]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/node.py", line 43, in <module>
[Detection3DArray.py-4]     from rclpy.client import Client
[Detection3DArray.py-4]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/client.py", line 22, in <module>
[Detection3DArray.py-4]     from rclpy.impl.implementation_singleton import rclpy_implementation as _rclpy
[Detection3DArray.py-4]   File "/opt/ros/galactic/lib/python3.8/site-packages/rclpy/impl/implementation_singleton.py", line 32, in <module>
[Detection3DArray.py-4]     rclpy_implementation = import_c_library('._rclpy_pybind11', package)
[Detection3DArray.py-4]   File "/opt/ros/galactic/lib/python3.8/site-packages/rpyutils/import_c_library.py", line 39, in import_c_library
[Detection3DArray.py-4]     return importlib.import_module(name, package=package)
[Detection3DArray.py-4]   File "/home/lin/software/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
[Detection3DArray.py-4]     return _bootstrap._gcd_import(name[level:], package, level)
[Detection3DArray.py-4] ModuleNotFoundError: No module named 'rclpy._rclpy_pybind11'
[Detection3DArray.py-4] The C extension '/opt/ros/galactic/lib/python3.8/site-packages/_rclpy_pybind11.cpython-39-x86_64-linux-gnu.so' isn't present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system' for possible solutions
[ERROR] [BoundingBox3D.py-1]: process has died [pid 80594, exit code 1, cmd '/home/lin/ros2_code/pillars_ws/install/vision_msgs_rviz_plugins/lib/vision_msgs_rviz_plugins/BoundingBox3D.py --ros-args -r __node:=boundingbox3d_test'].
[ERROR] [Detection3DArray.py-4]: process has died [pid 80600, exit code 1, cmd '/home/lin/ros2_code/pillars_ws/install/vision_msgs_rviz_plugins/lib/vision_msgs_rviz_plugins/Detection3DArray.py --ros-args -r __node:=detection3darray_test'].
[rviz2-5] [rospack] Error: package 'rviz_common' not found
[rviz2-5] [librospack]: error while executing command
[rviz2-5] [INFO] [1692688623.686536338] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-5] [INFO] [1692688623.686627491] [rviz2]: OpenGl version: 4.6 (GLSL 4.6)
[rviz2-5] [rospack] Error: package 'rviz_common' not found
[rviz2-5] [librospack]: error while executing command
[rviz2-5] [rospack] Error: package 'rviz_common' not found
[rviz2-5] [librospack]: error while executing command
[rviz2-5] [INFO] [1692688623.771178453] [rviz2]: Stereo is NOT SUPPORTED
[rviz2-5] [rospack] Error: package 'rviz_default_plugins' not found
[rviz2-5] [librospack]: error while executing command
[rviz2-5] [rospack] Error: package 'rviz_default_plugins' not found
[rviz2-5] [librospack]: error while executing command
[rviz2-5] [rospack] Error: package 'rviz_common' not found
[rviz2-5] [librospack]: error while executing command
[rviz2-5] [rospack] Error: package 'rviz_common' not found
[rviz2-5] [librospack]: error while executing command
[rviz2-5] [rospack] Error: package 'rviz_common' not found
[rviz2-5] [librospack]: error while executing command
[rviz2-5] /opt/ros/galactic/lib/rviz2/rviz2: symbol lookup error: /opt/ros/galactic/lib/librviz_common.so: undefined symbol: _ZNK12class_loader23MultiLibraryClassLoader27getAllAvailableClassLoadersEv
[ERROR] [rviz2-5]: process has died [pid 80602, exit code 127, cmd '/opt/ros/galactic/lib/rviz2/rviz2 -d /home/lin/ros2_code/pillars_ws/install/vision_msgs_rviz_plugins/share/vision_msgs_rviz_plugins/conf/conf.rviz --ros-args -r __node:=rviz2'].
~~~

**Comment by SteveMacenski** [comment]
I believe that you failed to install all of the dependencies using rosdep prior to running.

**Comment by SteveMacenski** [comment]
Closing due to inactivity
